global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'gocrypto'
    static_configs:
      - targets: ['gocrypto:8080']
    basic_auth:
      username: 'admin'
      password: 'admin12345'