apiVersion: v1
kind: Service
metadata:
  name: crypto
  labels:
    app: crypto
spec:
  selector:
    app: crypto
  ports:
    - name: "80"
      port: 80
      targetPort: 80
status:
  loadBalancer: {}