apiVersion: v1
kind: Service
metadata:
  name: crypto-service
  labels:
    app: crypto
spec:
  selector:
    app: crypto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer