apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  labels:
    app: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          image: ghcr.io/bypikod/go-crypto/notifier:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
status: {}