name: Update README on Push

on:
  push:
    branches:
      - main

jobs:
  push-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Check for README.md and promotions changes
        id: changes
        run: |
          readme_changed=false
          promotions_changed=false
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
            if [[ $file == 'README.md' ]]; then
              readme_changed=true
            fi
            if [[ $file == 'promotions/'* ]]; then
              promotions_changed=true
            fi
          done
          if [[ $readme_changed == 'true' || $promotions_changed == 'true' ]]; then
            echo "Changes detected at README."
            echo "::set-output name=readme_changed::$readme_changed"
            echo "::set-output name=promotions_changed::$promotions_changed"
          else
            echo "No changes detected at README."
            echo "::set-output name=readme_changed::false"
            echo "::set-output name=promotions_changed::false"
          fi
      - name: Push changes
        if: steps.changes.outputs.readme_changed == 'true' || steps.changes.outputs.promotions_changed == 'true'
        run: |
          git config --global user.email "46069238+ByPikod@users.noreply.github.com"
          git config --global user.name "Yahya Batulu"
          git push origin web
          git config --global user.email "yahyabatulu00@gmail.com"
          git config --global user.name "Your Name"
          git push origin web
